# Generated by Django 4.2.26 on 2025-11-27 16:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('preferred_language', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, upload_to='tourists/profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tourist_profiles',
            },
        ),
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=1000)),
                ('profile_picture', models.ImageField(upload_to='guides/profiles/')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(default=list)),
                ('half_day_price', models.DecimalField(decimal_places=2, help_text='Price for tours up to 4 hours', max_digits=10)),
                ('full_day_price', models.DecimalField(decimal_places=2, help_text='Price for tours 4-8 hours', max_digits=10)),
                ('extra_hour_price', models.DecimalField(decimal_places=2, help_text='Price per hour beyond 8 hours', max_digits=10)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_tours_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage_areas', models.ManyToManyField(related_name='guides', to='locations.wilaya')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guide_profiles',
            },
        ),
        migrations.CreateModel(
            name='GuideCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(upload_to='guides/certifications/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.guideprofile')),
            ],
            options={
                'db_table': 'guide_certifications',
            },
        ),
        migrations.AddIndex(
            model_name='guideprofile',
            index=models.Index(fields=['verification_status'], name='guide_profi_verific_8bed3b_idx'),
        ),
        migrations.AddIndex(
            model_name='guideprofile',
            index=models.Index(fields=['average_rating'], name='guide_profi_average_0b28a3_idx'),
        ),
        migrations.AddIndex(
            model_name='guideprofile',
            index=models.Index(fields=['created_at'], name='guide_profi_created_5636ac_idx'),
        ),
    ]
