# Generated by Django 4.2.26 on 2025-11-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidecertification',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='guidecertification',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='guidecertification',
            name='issuing_organization',
        ),
    ]
