# Generated by Django 4.2.26 on 2025-11-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_guidecertification_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('morning', 'Morning (8:00-12:00)'), ('afternoon', 'Afternoon (13:00-17:00)'), ('evening', 'Evening (18:00-22:00)'), ('full_day', 'Full Day (8:00-17:00)')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='profiles.guideprofile')),
            ],
            options={
                'db_table': 'guide_availability',
                'indexes': [models.Index(fields=['guide', 'date'], name='guide_avail_guide_i_e877a1_idx'), models.Index(fields=['date', 'is_available'], name='guide_avail_date_3eaba0_idx')],
                'unique_together': {('guide', 'date', 'time_slot')},
            },
        ),
    ]
