# Generated by Django 4.2.26 on 2025-11-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_guideavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidecertification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guidecertification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidecertification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidecertification',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='guidecertification',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
