# Generated by Django 4.2.26 on 2025-11-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_guidecertification_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidecertification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='guidecertification',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='guidecertification',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='guidecertification',
            name='issuing_organization',
        ),
        migrations.RemoveField(
            model_name='guidecertification',
            name='name',
        ),
    ]
