# Generated by Django 4.2.26 on 2025-11-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='communication_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='knowledge_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='punctuality_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='value_rating',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
