# Generated by Django 4.2.26 on 2025-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wilayas',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='wilayas_code_12b46c_idx'), models.Index(fields=['name_en'], name='wilayas_name_en_72256c_idx')],
            },
        ),
    ]
