# Generated by Django 4.2.26 on 2025-11-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Tour Inquiry', max_length=200)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='profiles.guideprofile')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='profiles.touristprofile')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('tourist', 'Tourist'), ('guide', 'Guide')], max_length=10)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'), models.Index(fields=['is_read'], name='messages_is_read_6a69c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomTourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Describe your ideal tour')),
                ('preferred_date', models.DateField()),
                ('duration_hours', models.PositiveIntegerField(help_text='Estimated duration in hours')),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('guide_response', models.TextField(blank=True)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alternative_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to='profiles.guideprofile')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to='profiles.touristprofile')),
            ],
            options={
                'db_table': 'custom_tour_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tourist', 'status'], name='custom_tour_tourist_ed1af8_idx'), models.Index(fields=['guide', 'status'], name='custom_tour_guide_i_a8cf75_idx'), models.Index(fields=['preferred_date'], name='custom_tour_preferr_6cd433_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tourist', 'last_message_at'], name='conversatio_tourist_d5550c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['guide', 'last_message_at'], name='conversatio_guide_i_e2e139_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('tourist', 'guide')},
        ),
    ]
