# Generated by Django 4.2.26 on 2025-11-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('morning', 'Morning (8:00-12:00)'), ('afternoon', 'Afternoon (13:00-17:00)'), ('evening', 'Evening (18:00-22:00)'), ('full_day', 'Full Day (8:00-17:00)')], default='morning', max_length=20)),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='profiles.touristprofile')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='bookings_status_51373b_idx'), models.Index(fields=['booking_date'], name='bookings_booking_2846e7_idx'), models.Index(fields=['tourist'], name='bookings_tourist_c14a4f_idx'), models.Index(fields=['created_at'], name='bookings_created_118d3e_idx')],
            },
        ),
    ]
