# Generated by Django 4.2.26 on 2025-11-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstatushistory',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingstatushistory',
            name='changed_by',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_request_813a6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_guide_i_182e5f_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='requested_date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='cancellation_reason',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='alternative_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='alternative_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_reference',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='custom_duration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guide_notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='requested_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tourist_notes',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='bookings_booking_2846e7_idx'),
        ),
        migrations.DeleteModel(
            name='BookingStatusHistory',
        ),
    ]
