# Generated by Django 4.2.26 on 2025-11-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_bookingstatushistory_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning (8:00-12:00)'), ('afternoon', 'Afternoon (13:00-17:00)'), ('evening', 'Evening (18:00-22:00)'), ('full_day', 'Full Day (8:00-17:00)')], default='morning', max_length=20),
        ),
    ]
