# Generated by Django 4.2.26 on 2025-11-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Duration in hours', max_digits=4)),
                ('max_group_size', models.PositiveIntegerField(default=8)),
                ('included_services', models.JSONField(default=list)),
                ('excluded_services', models.JSONField(default=list)),
                ('meeting_point', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS Latitude for departure point', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS Longitude for departure point', max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tags', models.JSONField(default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='profiles.guideprofile')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.wilaya')),
            ],
            options={
                'db_table': 'tours',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wilaya'], name='tours_wilaya__82f965_idx'), models.Index(fields=['status'], name='tours_status_a9697b_idx'), models.Index(fields=['price'], name='tours_price_277d95_idx'), models.Index(fields=['duration_hours'], name='tours_duratio_022746_idx'), models.Index(fields=['created_at'], name='tours_created_8be4fc_idx')],
            },
        ),
    ]
