# Generated by Django 4.2.26 on 2025-11-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Duration in hours', max_digits=4)),
                ('max_group_size', models.PositiveIntegerField(default=8)),
                ('included_services', models.JSONField(default=list)),
                ('excluded_services', models.JSONField(default=list)),
                ('meeting_point', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='profiles.guideprofile')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.wilaya')),
            ],
            options={
                'db_table': 'tours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='profiles.guideprofile')),
            ],
            options={
                'db_table': 'tour_availability',
                'indexes': [models.Index(fields=['guide', 'date'], name='tour_availa_guide_i_671e70_idx'), models.Index(fields=['date', 'is_available'], name='tour_availa_date_6db0d9_idx')],
                'unique_together': {('guide', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['wilaya'], name='tours_wilaya__82f965_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['status'], name='tours_status_a9697b_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['price'], name='tours_price_277d95_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['duration_hours'], name='tours_duratio_022746_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['created_at'], name='tours_created_8be4fc_idx'),
        ),
    ]
