# Generated by Django 4.2.26 on 2025-11-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourimage',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/images/'),
        ),
        migrations.DeleteModel(
            name='TourAvailability',
        ),
        migrations.DeleteModel(
            name='TourImage',
        ),
    ]
