# Generated by Django 4.2.26 on 2025-11-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tourimage_tour_tour_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, help_text='GPS Latitude for departure point', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, help_text='GPS Longitude for departure point', max_digits=9),
            preserve_default=False,
        ),
    ]
